---
- name: check if mongo already installed
  stat: path=/usr/bin/mongo
  register: mongo_bin

- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  when: mongo_bin.stat.exists == False

- name: MongoDB | Add 10Gen repository
  shell:
    echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    creates=/etc/apt/sources.list.d/mongodb-org-3.2.list
  when: mongo_bin.stat.exists == False

- name: install mongodb
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools
  when: mongo_bin.stat.exists == False

- name: MongoDB - stop server
  service: name=mongod state=stopped
  when: mongo_bin.stat.exists == False

# On next startup, a configuration file will be used
- name: copy configuration file
  copy: src=mongod.conf dest=/etc/mongod.conf mode=0644
  when: mongo_bin.stat.exists == False
